import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#515f78",
        "on-primary-container": "#74829d",
        "tertiary-fixed-dim": "#b6c8e4",
        background: "#041329",
        outline: "#8f9097",
        "surface-container-highest": "#27354c",
        "surface-container": "#112036",
        "secondary-fixed": "#ffdea5",
        "on-primary": "#233148",
        "surface-bright": "#2c3951",
        "inverse-on-surface": "#233148",
        "primary-fixed-dim": "#b9c7e4",
        "surface-container-low": "#0d1c32",
        "on-surface": "#d6e3ff",
        "on-tertiary": "#203148",
        "tertiary-fixed": "#d3e3ff",
        "on-error-container": "#ffdad6",
        "secondary-fixed-dim": "#e9c176",
        "surface-container-high": "#1c2a41",
        secondary: "#e9c176",
        primary: "#b9c7e4",
        error: "#ffb4ab",
        "on-secondary-container": "#dab36a",
        "tertiary-container": "#071a2f",
        "on-tertiary-fixed": "#091c32",
        "on-error": "#690005",
        "on-surface-variant": "#c5c6cd",
        "on-tertiary-fixed-variant": "#37485f",
        "on-primary-fixed-variant": "#39475f",
        "inverse-surface": "#d6e3ff",
        "surface-tint": "#b9c7e4",
        "surface-container-lowest": "#010e24",
        "on-secondary-fixed-variant": "#5d4201",
        "outline-variant": "#44474d",
        "secondary-container": "#604403",
        "on-primary-fixed": "#0d1c32",
        "on-background": "#d6e3ff",
        "surface-variant": "#27354c",
        "primary-fixed": "#d6e3ff",
        "on-secondary-fixed": "#261900",
        "primary-container": "#0a192f",
        surface: "#041329",
        "error-container": "#93000a",
        "on-secondary": "#412d00",
        tertiary: "#b6c8e4",
        "on-tertiary-container": "#72839d",
        "surface-dim": "#041329",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["var(--font-manrope)", "system-ui", "sans-serif"],
        body: ["var(--font-manrope)", "system-ui", "sans-serif"],
        label: ["var(--font-manrope)", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
} satisfies Config;

